version: '3.3'
services:
        gateway:
          build: ./gateway
          stdin_open: true
          container_name: "gateway"
          hostname: "gateway"
          tty: true
          ports:
            - "50051:50051"
          networks:
            - backend
            - midend
          depends_on:
            - mongodb
          environment:
            - MONGO_URL=mongodb://mongodb:27017/app_development
        api:
            build: ./handy_api
            stdin_open: true
            container_name: "api"
            hostname: "api"
            depends_on:
            - gateway
            networks:
              - midend
            ports:
              - "4000:4000"
        mongodb:
          image: aashreys/mongo-auth:latest
          container_name: "mongodb"
          environment:
            - AUTH=yes
            - MONGODB_ADMIN_USER=admin
            - MONGODB_ADMIN_PASS=applepie
            - MONGODB_APPLICATION_DATABASE=gateway
            - MONGODB_APPLICATION_USER=gateway_dev_user
            - MONGODB_APPLICATION_PASS=gateway_dev_pass
          ports:
              - 27017:27017
          networks:  
            - backend
#          command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:  
  backend:
    driver: bridge
  midend:
    driver: bridge
